package com.evergent.corejava.exceptionhandling;

public class ExceptionDemo3 {
	String name=null;
	int k=0;
	public void myData() {
		try {
			System.out.println("one");
			System.out.println(name.length());
			int t=10/k;
			System.out.println(t);
			System.out.println("end");
		}
		
		catch(ArithmeticException e) {
			System.out.println("i can handle "+e);
		}
		//catch(NullPointerException e) {
			//System.out.println("i can handle "+e);
		//}
		
		
	}

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		ExceptionDemo3 ed2=new ExceptionDemo3();
		ed2.myData();

	}

}
